# Generated by Django 4.2.20 on 2025-05-12 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hospitalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=40)),
                ('services', models.CharField(max_length=255)),
                ('departments', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'app_hospitals',
            },
        ),
        migrations.CreateModel(
            name='doctorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('degrees', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('isSaturday', models.BooleanField(default=False)),
                ('isSunday', models.BooleanField(default=False)),
                ('isMonday', models.BooleanField(default=False)),
                ('isTuesday', models.BooleanField(default=False)),
                ('isWednesday', models.BooleanField(default=False)),
                ('isThursday', models.BooleanField(default=False)),
                ('isFriday', models.BooleanField(default=False)),
                ('apointmentTime', models.CharField(max_length=100)),
                ('availableTime', models.CharField(max_length=100)),
                ('fees', models.CharField(max_length=50)),
                ('rating', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hospitalmodel')),
            ],
            options={
                'db_table': 'app_doctors',
            },
        ),
        migrations.CreateModel(
            name='ambulanceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('phone', models.CharField(max_length=15)),
                ('services', models.CharField(max_length=255)),
                ('fees', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hospitalmodel')),
            ],
            options={
                'db_table': 'app_ambulances',
            },
        ),
    ]
